### ISSUE TITLE
启动时出错

### ISSUE THREAD

**Issue by TotoWang-hhh** [sst4rb0y/mc_serversAllow#1]
log

```
Error occurred during initialization of VM
agent library failed to init: instrument
Error opening zip file or JAR manifest missing : \.minecraft\versions\1.16.5-Fabric 0.14.19-OptiFine_G8\agnet-1.0-SNAPSHOT.jar
```

参数设置

jvm参数头

```
-javaagent:"\.minecraft\versions\1.16.5-Fabric 0.14.19-OptiFine_G8\agnet-1.0-SNAPSHOT.jar"
```

**Comment by ylca0** [comment]
路径换成左斜杠试试---- 回复的原邮件 ***@***.***>发送日期2023年07月06日 18:01 ***@***.***> ***@***.***>主题[sst4rb0y/mc_serversAllow] 启动时出错 (Issue #1)
log
Error occurred during initialization of VM
agent library failed to init: instrument
Error opening zip file or JAR manifest missing : \.minecraft\versions\1.16.5-Fabric 0.14.19-OptiFine_G8\agnet-1.0-SNAPSHOT.jar

参数设置
jvm参数头
-javaagent:"\.minecraft\versions\1.16.5-Fabric 0.14.19-OptiFine_G8\agnet-1.0-SNAPSHOT.jar"


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/sst4rb0y/mc_serversAllow/issues/1",
"url": "https://github.com/sst4rb0y/mc_serversAllow/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
